### ISSUE TITLE
Release Date for GPT-SoVITS Modifications

### ISSUE THREAD

**Issue by Bubarinokk** [YoMio-Tech-Inc/GPT-SoVITS2#1]
Hello, I would like to know when these modifications in GPT-SoVITS will be released (I don't know if they have been released yet).

**Comment by JunityZhan** [comment]
Hi,
This is a repo for GPT-SoVITS2. If you are asking about when does GPT-SoVITS2 release, then I would say probably before mid July, and the pretrained model would be before August.
Best

**Comment by Bubarinokk** [comment]
> Hi, This is a repo for GPT-SoVITS2. If you are asking about when does GPT-SoVITS2 release, then I would say probably before mid July, and the pretrained model would be before August. Best

Ahh ok! Another question: Will the multilingual model be included in the fine-tuning as well?

**Comment by JunityZhan** [comment]
GPT-SoVITS2 is **multilingual** TTS System, which means you can input any language into it. However, the performance may vary based on training dataset.

**Comment by Bubarinokk** [comment]
> GPT-SoVITS2 is **multilingual** TTS System, which means you can input any language into it. However, the performance may vary based on training dataset.

I was referring to whether the changes in GPT-SoVITS2 (including the addition of new languages) will be included in the training/fine-tuning.

**Comment by JunityZhan** [comment]
There is a concept should be noted. While GPT-SoVITS do need manually add a new language, GPT-SoVITS2 does not explicitly "add" new language. It works like a LLM like ChatGPT, you can input any language into it. 
In this case, if you are refereing if there is other language training dataset, I would say I will add them if I see there is good open-source multi-lingual TTS dataset, then it will be added to the training. Specifically we can expect GPT-SoVITS2 works best on English, Chinese, Japanese, Korean, but other language like Spanish... would also be added if the multi-lingual TTS training dataset is including them.

**Comment by abf524** [comment]
Hi, i want to ask something about gpt sovits, is gpt sovits will also fork in google colab? and can gpt sovits support Indonesian language?

**Comment by JunityZhan** [comment]
If you have a lot of Indonesian dataset, you could send them here: zlk1715069210@gmail.com. If they are trained in the pretrained model, you can easily use GPT SOVITS2 in Indonesian language without further finetuning

**Comment by AngryBearr** [comment]
There is a trained model for russian language, will you add that as well? It's specifically trained so that it would have the knowledge of the emphasis when it encounters the `+` sign it knows that it has to put the emphasis on a voul.
Here is the link to the model on the [HF](https://huggingface.co/alphacep/vosk-tts-ru-gpt-sovits) and a [repo link](https://github.com/alphacep/vosk-tts/tree/master/gpt-sovits) with the inference code to run the model.
