### ISSUE TITLE
dataset 定义

### ISSUE THREAD

**Issue by xinge333** [YoMio-Tech-Inc/GPT-SoVITS2#10]
https://github.com/YoMio-Tech-Inc/GPT-SoVITS2/blob/e84b978b62228455b7e76fde1effe88433ec8f79/GPT_SoVITS/AR/data/dataset.py#L178

这儿__getitem__ 里面是不是把phoneme_ids和phoneme_ids_lens给漏掉啦？

**Comment by JunityZhan** [comment]
一个是GPT的dataset还没写，另外一个是GSV2没有phoneme，所以是没有的
