### ISSUE TITLE
Colab Version of GPT-SoVits2

### ISSUE THREAD

**Issue by abf524** [YoMio-Tech-Inc/GPT-SoVITS2#5]
i want to know if you had plan for GPT-SoVITS2 webui will also available on Google Colab when released. also will it support Indonesian Language? and how to train the voice model with this GPT-SoVITS2? Thanks

**Comment by TheRC4** [comment]
I'm not a developer, but I'll try to help you out:

1- I'm not sure if it will be available on Google Colab, but most likely.
2- If you carefully read [README.md](https://github.com/YoMio-Tech-Inc/GPT-SoVITS2/blob/main/docs/en/README.md), you will find this line: Native support for multiple languages: Not limited to Chinese, Japanese, and English, **but supports any language in the world.**
3- GPT-SoVITS2 has not been released yet, but I believe the training method will be similar to that of the original GPT-SoVITS repository.
