### ISSUE TITLE
Train guide and endoder question

### ISSUE THREAD

**Issue by acul3** [YoMio-Tech-Inc/GPT-SoVITS2#9]
Hello very nice project and idea, would like to contribute if i can

Since the base original doesnt give clear or consise instruction how to train from scratch.

Can you write/guide or give script how to train it from scratch? ..maybe i can help if there is code or guide to start

Also
Have you consider whisper-small as encoder, from my experience whisper has rich feature and act as excelent encoder

**Comment by JunityZhan** [comment]
I am still working on the training code, and if you are asking the GPT-SoVITS repo, you may open an issue there.
